In [1]:
import csv
import pandas as pd
import numpy as np
import sys
from scipy import stats
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('Dataset.csv',nrows=2000, encoding='utf-8')
data.columns

Index(['npi', 'nppes_provider_last_org_name', 'nppes_provider_first_name',
       'nppes_provider_mi', 'nppes_credentials', 'nppes_provider_gender',
       'nppes_entity_code', 'nppes_provider_street1', 'nppes_provider_street2',
       'nppes_provider_city', 'nppes_provider_zip5', 'nppes_provider_zip4',
       'nppes_provider_state', 'nppes_provider_country',
       'specialty_description', 'description_flag',
       'medicare_prvdr_enroll_status', 'total_claim_count',
       'total_30_day_fill_count', 'total_drug_cost', 'total_day_supply',
       'bene_count', 'ge65_suppress_flag', 'total_claim_count_ge65',
       'total_30_day_fill_count_ge65', 'total_drug_cost_ge65',
       'total_day_supply_ge65', 'bene_count_ge65_suppress_flag',
       'bene_count_ge65', 'brand_suppress_flag', 'brand_claim_count',
       'brand_drug_cost', 'generic_suppress_flag', 'generic_claim_count',
       'generic_drug_cost', 'other_suppress_flag', 'other_claim_count',
       'other_drug_cost', 'mapd_suppress_flag', 'mapd_claim_count',
       'mapd_drug_cost', 'pdp_suppress_flag', 'pdp_claim_count',
       'pdp_drug_cost', 'lis_suppress_flag', 'lis_claim_count',
       'lis_drug_cost', 'nonlis_suppress_flag', 'nonlis_claim_count',
       'nonlis_drug_cost', 'opioid_claim_count', 'opioid_drug_cost',
       'opioid_day_supply', 'opioid_bene_count', 'opioid_prescriber_rate',
       'antibiotic_claim_count', 'antibiotic_drug_cost',
       'antibiotic_bene_count', 'hrm_ge65_suppress_flag',
       'hrm_claim_count_ge65', 'hrm_drug_cost_ge65',
       'hrm_bene_ge65_suppress_flag', 'hrm_bene_count_ge65',
       'antipsych_ge65_suppress_flag', 'antipsych_claim_count_ge65',
       'antipsych_drug_cost_ge65', 'antipsych_bene_ge65_suppress_flg',
       'antipsych_bene_count_ge65', 'average_age_of_beneficiaries',
       'beneficiary_age_less_65_count', 'beneficiary_age_65_74_count',
       'beneficiary_age_75_84_count', 'beneficiary_age_greater_84_count',
       'beneficiary_female_count', 'beneficiary_male_count',
       'beneficiary_race_white_count', 'beneficiary_race_black_count',
       'beneficiary_race_asian_pi_count', 'beneficiary_race_hispanic_count',
       'beneficiary_race_nat_ind_count', 'beneficiary_race_other_count',
       'beneficiary_nondual_count', 'beneficiary_dual_count',
       'beneficiary_average_risk_score'],
      dtype='object')

In [3]:
data.drop(['npi',
           'nppes_provider_last_org_name',
           'nppes_provider_first_name',
           'nppes_provider_mi',
           'nppes_credentials',
           'nppes_provider_street1',
           'nppes_provider_street2',
           'nppes_provider_zip4',
           'nppes_provider_country',
           'description_flag',
           'ge65_suppress_flag',
           'total_claim_count_ge65',
           'total_30_day_fill_count_ge65',
           'total_drug_cost_ge65',
           'total_day_supply_ge65',
           'bene_count_ge65_suppress_flag',
           'bene_count_ge65',
           'brand_suppress_flag',
           'generic_suppress_flag',
           'other_suppress_flag',
           'mapd_suppress_flag',
           'pdp_suppress_flag',
           'lis_suppress_flag',
           'nonlis_suppress_flag',
           'opioid_prescriber_rate',
           'hrm_ge65_suppress_flag',
           'hrm_claim_count_ge65',
           'hrm_drug_cost_ge65',
           'hrm_bene_ge65_suppress_flag',
           'hrm_bene_count_ge65',
           'antipsych_ge65_suppress_flag',
           'antipsych_claim_count_ge65',
           'antipsych_drug_cost_ge65',
           'antipsych_bene_ge65_suppress_flg',
           'antipsych_bene_count_ge65',
           'beneficiary_age_less_65_count',
           'beneficiary_age_65_74_count',
           'beneficiary_age_75_84_count',
           'beneficiary_age_greater_84_count',
         ],axis = 1,inplace = True)

data.index = range(len(data))
data.replace({',':'','\$':''},regex= True,inplace = True)
#data.nppes_entity_code.replace({'O':0,'I':1},regex=True,inplace=True)
print(data.columns)

Index(['nppes_provider_gender', 'nppes_entity_code', 'nppes_provider_city',
       'nppes_provider_zip5', 'nppes_provider_state', 'specialty_description',
       'medicare_prvdr_enroll_status', 'total_claim_count',
       'total_30_day_fill_count', 'total_drug_cost', 'total_day_supply',
       'bene_count', 'brand_claim_count', 'brand_drug_cost',
       'generic_claim_count', 'generic_drug_cost', 'other_claim_count',
       'other_drug_cost', 'mapd_claim_count', 'mapd_drug_cost',
       'pdp_claim_count', 'pdp_drug_cost', 'lis_claim_count', 'lis_drug_cost',
       'nonlis_claim_count', 'nonlis_drug_cost', 'opioid_claim_count',
       'opioid_drug_cost', 'opioid_day_supply', 'opioid_bene_count',
       'antibiotic_claim_count', 'antibiotic_drug_cost',
       'antibiotic_bene_count', 'average_age_of_beneficiaries',
       'beneficiary_female_count', 'beneficiary_male_count',
       'beneficiary_race_white_count', 'beneficiary_race_black_count',
       'beneficiary_race_asian_pi_count', 'beneficiary_race_hispanic_count',
       'beneficiary_race_nat_ind_count', 'beneficiary_race_other_count',
       'beneficiary_nondual_count', 'beneficiary_dual_count',
       'beneficiary_average_risk_score'],
      dtype='object')

In [4]:
data['nppes_provider_gender'] = data['nppes_provider_gender'].astype(str)
data['nppes_entity_code'] = data['nppes_entity_code'].astype(str)
data['nppes_provider_zip5'] = data['nppes_provider_zip5'].astype(str)
data['nppes_provider_state'] = data['nppes_provider_state'].astype(str)
data['specialty_description'] = data['specialty_description'].astype(str)

In [5]:
data.head(25)

,nppes_provider_gender,nppes_entity_code,nppes_provider_city,nppes_provider_zip5,nppes_provider_state,specialty_description,medicare_prvdr_enroll_status,total_claim_count,total_30_day_fill_count,total_drug_cost,...,beneficiary_male_count,beneficiary_race_white_count,beneficiary_race_black_count,beneficiary_race_asian_pi_count,beneficiary_race_hispanic_count,beneficiary_race_nat_ind_count,beneficiary_race_other_count,beneficiary_nondual_count,beneficiary_dual_count,beneficiary_average_risk_score
0,nan,O,NEW YORK,10016,NY,Pharmacist,N,18,19,885.23,...,NaN,NaN,NaN,0.0,NaN,0.0,0.0,12,0,1.7148
1,nan,O,CANOGA PARK,91303,CA,Clinic/Center,N,84,84,1643.43,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,nan,O,MIAMI LAKES,33014,FL,Internal Medicine,N,29,48.4,327.20,...,11.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,1.3811
3,nan,O,AVENTURA,33180,FL,Urology,N,27,31,1125.76,...,NaN,NaN,NaN,0.0,NaN,0.0,0.0,NaN,NaN,2.2233
4,nan,O,BELLINGHAM,98225,WA,Dentist,N,28,34,2006.04,...,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,1.3712
5,nan,O,ARUNDEL,4046,ME,Dentist,N,17,17,121.89,...,NaN,NaN,0.0,NaN,0,0.0,0.0,NaN,NaN,1.4168
6,nan,O,MODESTO,95351,CA,Psychiatry & Neurology,N,13,13,2512.93,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,nan,O,HARAHAN,70123,LA,Ophthalmology,N,29,30.7,2685.19,...,NaN,NaN,NaN,0.0,0,0.0,0.0,NaN,NaN,1.7843
8,nan,O,SUNNYSIDE,11104,NY,Family Practice,N,55,111,6231.29,...,NaN,NaN,NaN,0.0,0,0.0,0.0,NaN,NaN,1.0832
9,nan,O,BEVERLY HILLS,90211,CA,Internal Medicine,N,48,68.3,2100.93,...,NaN,NaN,0.0,NaN,NaN,0.0,0.0,NaN,NaN,1.0868
10,nan,O,MIAMI,33186,FL,Specialist,N,116,117.3,8588.20,...,NaN,NaN,0.0,0.0,NaN,0.0,0.0,0,12,1.9028
11,nan,O,OZONE PARK,11416,NY,Dentist,N,11,11,55.77,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,nan,O,SPOKANE,99204,WA,Family Practice,N,56,59.9,3940.85,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,nan,O,TOMS RIVER,8755,NJ,Internal Medicine,N,35,70,4020.35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,nan,O,PALM DESERT,92260,CA,Family Practice,N,23,66.6,1316.09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,nan,O,NY,10028,NY,Psychiatry & Neurology,N,12,14,863.61,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,nan,O,HERRIN,62948,IL,Internal Medicine,N,19,57,3393.20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,nan,O,DORAL,33166,FL,Internal Medicine,N,223,223,13489.86,...,NaN,0,NaN,0.0,NaN,0.0,0.0,NaN,NaN,2.8868
18,nan,O,JERSEY CITY,7304,NJ,Internal Medicine,N,57,59.3,2482.90,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,nan,O,MIAMI,33173,FL,Internal Medicine,N,38,108,1790.58,...,NaN,NaN,0.0,0.0,NaN,0.0,NaN,NaN,NaN,0.9756
20,nan,O,LOS ANGELES,90024,CA,Clinic/Center,N,12,18,657.36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,M,I,MINEOLA,11501,NY,Pediatric Medicine,N,134,213,13231.48,...,NaN,17,NaN,NaN,NaN,0.0,0.0,NaN,NaN,1.6460
22,nan,O,PORTLAND,97209,OR,Naturopath,N,21,32.8,1577.09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,M,I,STAMFORD,6902,CT,Psychiatry,E,4504,4656.40,399238.49,...,79.0,92,NaN,NaN,59,NaN,NaN,24,176,1.5358
24,nan,O,HUNTINGTON PARK,90255,CA,Ophthalmology,N,82,84.3,5446.90,...,13.0,17,0.0,NaN,NaN,0.0,NaN,NaN,NaN,1.9084

In [6]:
data['nppes_provider_gender'] = data['nppes_provider_gender'].replace('nan','Org')
data.fillna(0, inplace=True)
data.head(15)

,nppes_provider_gender,nppes_entity_code,nppes_provider_city,nppes_provider_zip5,nppes_provider_state,specialty_description,medicare_prvdr_enroll_status,total_claim_count,total_30_day_fill_count,total_drug_cost,...,beneficiary_male_count,beneficiary_race_white_count,beneficiary_race_black_count,beneficiary_race_asian_pi_count,beneficiary_race_hispanic_count,beneficiary_race_nat_ind_count,beneficiary_race_other_count,beneficiary_nondual_count,beneficiary_dual_count,beneficiary_average_risk_score
0,Org,O,NEW YORK,10016,NY,Pharmacist,N,18,19,885.23,...,0.0,0,0.0,0.0,0,0.0,0.0,12,0,1.7148
1,Org,O,CANOGA PARK,91303,CA,Clinic/Center,N,84,84,1643.43,...,0.0,0,0.0,0.0,0,0.0,0.0,0,0,0.0000
2,Org,O,MIAMI LAKES,33014,FL,Internal Medicine,N,29,48.4,327.20,...,11.0,0,0.0,0.0,0,0.0,0.0,0,0,1.3811
3,Org,O,AVENTURA,33180,FL,Urology,N,27,31,1125.76,...,0.0,0,0.0,0.0,0,0.0,0.0,0,0,2.2233
4,Org,O,BELLINGHAM,98225,WA,Dentist,N,28,34,2006.04,...,0.0,0,0.0,0.0,0,0.0,0.0,0,0,1.3712
5,Org,O,ARUNDEL,4046,ME,Dentist,N,17,17,121.89,...,0.0,0,0.0,0.0,0,0.0,0.0,0,0,1.4168
6,Org,O,MODESTO,95351,CA,Psychiatry & Neurology,N,13,13,2512.93,...,0.0,0,0.0,0.0,0,0.0,0.0,0,0,0.0000
7,Org,O,HARAHAN,70123,LA,Ophthalmology,N,29,30.7,2685.19,...,0.0,0,0.0,0.0,0,0.0,0.0,0,0,1.7843
8,Org,O,SUNNYSIDE,11104,NY,Family Practice,N,55,111,6231.29,...,0.0,0,0.0,0.0,0,0.0,0.0,0,0,1.0832
9,Org,O,BEVERLY HILLS,90211,CA,Internal Medicine,N,48,68.3,2100.93,...,0.0,0,0.0,0.0,0,0.0,0.0,0,0,1.0868
10,Org,O,MIAMI,33186,FL,Specialist,N,116,117.3,8588.20,...,0.0,0,0.0,0.0,0,0.0,0.0,0,12,1.9028
11,Org,O,OZONE PARK,11416,NY,Dentist,N,11,11,55.77,...,0.0,0,0.0,0.0,0,0.0,0.0,0,0,0.0000
12,Org,O,SPOKANE,99204,WA,Family Practice,N,56,59.9,3940.85,...,0.0,0,0.0,0.0,0,0.0,0.0,0,0,0.0000
13,Org,O,TOMS RIVER,8755,NJ,Internal Medicine,N,35,70,4020.35,...,0.0,0,0.0,0.0,0,0.0,0.0,0,0,0.0000
14,Org,O,PALM DESERT,92260,CA,Family Practice,N,23,66.6,1316.09,...,0.0,0,0.0,0.0,0,0.0,0.0,0,0,0.0000

In [7]:
# try:
#     data['generic_brand_ratio']= data['generic_claim_count']/ data['brand_claim_count']
# except ZeroDivisionError:
#     data['generic_brand_ratio'] = 1

# data.head(50)

# order_df['Value'] = order_df.apply(lambda row: (row['Prices']*row['Amount']
#                                                if row['Action']=='Sell'
#                                                else -row['Prices']*row['Amount']),
#                                    axis=1)

# data['generic_brand_ratio'] = data.apply(lambda row: (int(data['generic_claim_count']).replace(',', '')/int(data['brand_claim_count']).replace(',', '')
#                                                       if int(row['brand_claim_count'])!=0                                                     
#                                                       else 1), axis=1)

# data['generic_brand_ratio'] = pd.Series(np.random.randn(200), index=data.index)

# for index, row in data.iterrows():
    
#     brand_claim_count = str(row['brand_claim_count']).replace(',','')
#     generic_claim_count = str(row['generic_claim_count']).replace(',','')
    
        
#     if(int(brand_claim_count)!=0):
#         data[row]['generic_brand_ratio'] = float(generic_claim_count)/float(brand_claim_count)
#     else:
#         data[row]['generic_brand_ratio'] = 1



ratio = pd.DataFrame(columns=['generic_brand_ratio'])

generic = data.generic_claim_count
brand = data.brand_claim_count

for row in range(len(brand)):
    generic[row] = str(generic[row]).replace(',','')
    brand[row] = str(brand[row]).replace(',','')
    
    if int(brand[row])!=0:
        ratio.loc[row] = float(generic[row])/float(brand[row])
    elif int(generic[row])!=0:
        ratio.loc[row] = generic[row]
    else:
        ratio.loc[row] = 'None'
        
data['generic_brand_ratio'] = ratio
           
temp = data[['generic_claim_count','brand_claim_count','generic_brand_ratio']]
data.head(15)

C:\Users\sanke\Anaconda3\lib\site-packages\ipykernel_launcher.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\sanke\Anaconda3\lib\site-packages\ipykernel_launcher.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,nppes_provider_gender,nppes_entity_code,nppes_provider_city,nppes_provider_zip5,nppes_provider_state,specialty_description,medicare_prvdr_enroll_status,total_claim_count,total_30_day_fill_count,total_drug_cost,...,beneficiary_race_white_count,beneficiary_race_black_count,beneficiary_race_asian_pi_count,beneficiary_race_hispanic_count,beneficiary_race_nat_ind_count,beneficiary_race_other_count,beneficiary_nondual_count,beneficiary_dual_count,beneficiary_average_risk_score,generic_brand_ratio
0,Org,O,NEW YORK,10016,NY,Pharmacist,N,18,19,885.23,...,0,0.0,0.0,0,0.0,0.0,12,0,1.7148,None
1,Org,O,CANOGA PARK,91303,CA,Clinic/Center,N,84,84,1643.43,...,0,0.0,0.0,0,0.0,0.0,0,0,0.0000,5.46154
2,Org,O,MIAMI LAKES,33014,FL,Internal Medicine,N,29,48.4,327.20,...,0,0.0,0.0,0,0.0,0.0,0,0,1.3811,None
3,Org,O,AVENTURA,33180,FL,Urology,N,27,31,1125.76,...,0,0.0,0.0,0,0.0,0.0,0,0,2.2233,None
4,Org,O,BELLINGHAM,98225,WA,Dentist,N,28,34,2006.04,...,0,0.0,0.0,0,0.0,0.0,0,0,1.3712,None
5,Org,O,ARUNDEL,4046,ME,Dentist,N,17,17,121.89,...,0,0.0,0.0,0,0.0,0.0,0,0,1.4168,17
6,Org,O,MODESTO,95351,CA,Psychiatry & Neurology,N,13,13,2512.93,...,0,0.0,0.0,0,0.0,0.0,0,0,0.0000,None
7,Org,O,HARAHAN,70123,LA,Ophthalmology,N,29,30.7,2685.19,...,0,0.0,0.0,0,0.0,0.0,0,0,1.7843,None
8,Org,O,SUNNYSIDE,11104,NY,Family Practice,N,55,111,6231.29,...,0,0.0,0.0,0,0.0,0.0,0,0,1.0832,1.75
9,Org,O,BEVERLY HILLS,90211,CA,Internal Medicine,N,48,68.3,2100.93,...,0,0.0,0.0,0,0.0,0.0,0,0,1.0868,1.4
10,Org,O,MIAMI,33186,FL,Specialist,N,116,117.3,8588.20,...,0,0.0,0.0,0,0.0,0.0,0,12,1.9028,77
11,Org,O,OZONE PARK,11416,NY,Dentist,N,11,11,55.77,...,0,0.0,0.0,0,0.0,0.0,0,0,0.0000,11
12,Org,O,SPOKANE,99204,WA,Family Practice,N,56,59.9,3940.85,...,0,0.0,0.0,0,0.0,0.0,0,0,0.0000,None
13,Org,O,TOMS RIVER,8755,NJ,Internal Medicine,N,35,70,4020.35,...,0,0.0,0.0,0,0.0,0.0,0,0,0.0000,0.842105
14,Org,O,PALM DESERT,92260,CA,Family Practice,N,23,66.6,1316.09,...,0,0.0,0.0,0,0.0,0.0,0,0,0.0000,None

In [8]:
# count = 0
# for index, row in data.iterrows():
#     if(row.generic_brand_ratio =='None'):
#         count = count + 1
#         data.drop(data.index[index], inplace= True)
# print(count)
count = 0
indices = []
for index, row in enumerate(data.generic_brand_ratio):
    if(row=='None'):
        count= count + 1
        indices.append(index)
print("Rows deleted {}".format(count))

data.drop(data.index[indices], inplace = True)

Rows deleted 566

In [9]:
temp = data[['generic_claim_count','brand_claim_count','generic_brand_ratio']]
temp.head(15)

   generic_claim_count brand_claim_count generic_brand_ratio
1                   71                13             5.46154
5                   17                 0                  17
8                   35                20                1.75
9                   28                20                 1.4
10                  77                 0                  77
11                  11                 0                  11
13                  16                19            0.842105
17                 163                 0                 163
18                  33                 0                  33
21                  89                45             1.97778
23                3772               732             5.15301
24                  33                49            0.673469
27                 137                33             4.15152
28                  54                35             1.54286
29                 108                76             1.42105

In [10]:
data.index = range(len(data))
ratio = data.generic_brand_ratio
category= pd.DataFrame(columns=['Preference'])

gcount=0
bcount=0

for index,row in enumerate(ratio):
    if(float(row) >0.0):
        category.loc[index]='G'
        gcount= gcount + 1
        
    else:
        category.loc[index]='B'
        bcount= bcount + 1

data['Preference']= category

print("Generic count {}".format(gcount))
print("Brand count {}".format(bcount))
temp_data = data[['generic_brand_ratio','Preference']]

# data.drop('generic_brand_ratio')
# data.drop('generic_claim_count')
# data.drop('brand_claim_count')

del data['generic_brand_ratio']
del data['generic_claim_count']
del data['brand_claim_count']

print(data.columns)

Generic count 1407
Brand count 27
Index(['nppes_provider_gender', 'nppes_entity_code', 'nppes_provider_city',
       'nppes_provider_zip5', 'nppes_provider_state', 'specialty_description',
       'medicare_prvdr_enroll_status', 'total_claim_count',
       'total_30_day_fill_count', 'total_drug_cost', 'total_day_supply',
       'bene_count', 'brand_drug_cost', 'generic_drug_cost',
       'other_claim_count', 'other_drug_cost', 'mapd_claim_count',
       'mapd_drug_cost', 'pdp_claim_count', 'pdp_drug_cost', 'lis_claim_count',
       'lis_drug_cost', 'nonlis_claim_count', 'nonlis_drug_cost',
       'opioid_claim_count', 'opioid_drug_cost', 'opioid_day_supply',
       'opioid_bene_count', 'antibiotic_claim_count', 'antibiotic_drug_cost',
       'antibiotic_bene_count', 'average_age_of_beneficiaries',
       'beneficiary_female_count', 'beneficiary_male_count',
       'beneficiary_race_white_count', 'beneficiary_race_black_count',
       'beneficiary_race_asian_pi_count', 'beneficiary_race_hispanic_count',
       'beneficiary_race_nat_ind_count', 'beneficiary_race_other_count',
       'beneficiary_nondual_count', 'beneficiary_dual_count',
       'beneficiary_average_risk_score', 'Preference'],
      dtype='object')

In [11]:
#testing data
test = pd.read_csv('Dataset.csv',skiprows=2000, nrows=2000,encoding='utf-8', names=['npi', 'nppes_provider_last_org_name', 'nppes_provider_first_name',
       'nppes_provider_mi', 'nppes_credentials', 'nppes_provider_gender',
       'nppes_entity_code', 'nppes_provider_street1', 'nppes_provider_street2',
       'nppes_provider_city', 'nppes_provider_zip5', 'nppes_provider_zip4',
       'nppes_provider_state', 'nppes_provider_country',
       'specialty_description', 'description_flag',
       'medicare_prvdr_enroll_status', 'total_claim_count',
       'total_30_day_fill_count', 'total_drug_cost', 'total_day_supply',
       'bene_count', 'ge65_suppress_flag', 'total_claim_count_ge65',
       'total_30_day_fill_count_ge65', 'total_drug_cost_ge65',
       'total_day_supply_ge65', 'bene_count_ge65_suppress_flag',
       'bene_count_ge65', 'brand_suppress_flag', 'brand_claim_count',
       'brand_drug_cost', 'generic_suppress_flag', 'generic_claim_count',
       'generic_drug_cost', 'other_suppress_flag', 'other_claim_count',
       'other_drug_cost', 'mapd_suppress_flag', 'mapd_claim_count',
       'mapd_drug_cost', 'pdp_suppress_flag', 'pdp_claim_count',
       'pdp_drug_cost', 'lis_suppress_flag', 'lis_claim_count',
       'lis_drug_cost', 'nonlis_suppress_flag', 'nonlis_claim_count',
       'nonlis_drug_cost', 'opioid_claim_count', 'opioid_drug_cost',
       'opioid_day_supply', 'opioid_bene_count', 'opioid_prescriber_rate',
       'antibiotic_claim_count', 'antibiotic_drug_cost',
       'antibiotic_bene_count', 'hrm_ge65_suppress_flag',
       'hrm_claim_count_ge65', 'hrm_drug_cost_ge65',
       'hrm_bene_ge65_suppress_flag', 'hrm_bene_count_ge65',
       'antipsych_ge65_suppress_flag', 'antipsych_claim_count_ge65',
       'antipsych_drug_cost_ge65', 'antipsych_bene_ge65_suppress_flg',
       'antipsych_bene_count_ge65', 'average_age_of_beneficiaries',
       'beneficiary_age_less_65_count', 'beneficiary_age_65_74_count',
       'beneficiary_age_75_84_count', 'beneficiary_age_greater_84_count',
       'beneficiary_female_count', 'beneficiary_male_count',
       'beneficiary_race_white_count', 'beneficiary_race_black_count',
       'beneficiary_race_asian_pi_count', 'beneficiary_race_hispanic_count',
       'beneficiary_race_nat_ind_count', 'beneficiary_race_other_count',
       'beneficiary_nondual_count', 'beneficiary_dual_count',
       'beneficiary_average_risk_score'])


test.drop(['npi',
           'nppes_provider_last_org_name',
           'nppes_provider_first_name',
           'nppes_provider_mi',
           'nppes_credentials',
           'nppes_provider_street1',
           'nppes_provider_street2',
           'nppes_provider_zip4',
           'nppes_provider_country',
           'description_flag',
           'ge65_suppress_flag',
           'total_claim_count_ge65',
           'total_30_day_fill_count_ge65',
           'total_drug_cost_ge65',
           'total_day_supply_ge65',
           'bene_count_ge65_suppress_flag',
           'bene_count_ge65',
           'brand_suppress_flag',
           'generic_suppress_flag',
           'other_suppress_flag',
           'mapd_suppress_flag',
           'pdp_suppress_flag',
           'lis_suppress_flag',
           'nonlis_suppress_flag',
           'opioid_prescriber_rate',
           'hrm_ge65_suppress_flag',
           'hrm_claim_count_ge65',
           'hrm_drug_cost_ge65',
           'hrm_bene_ge65_suppress_flag',
           'hrm_bene_count_ge65',
           'antipsych_ge65_suppress_flag',
           'antipsych_claim_count_ge65',
           'antipsych_drug_cost_ge65',
           'antipsych_bene_ge65_suppress_flg',
           'antipsych_bene_count_ge65',
           'beneficiary_age_less_65_count',
           'beneficiary_age_65_74_count',
           'beneficiary_age_75_84_count',
           'beneficiary_age_greater_84_count',
         ],axis = 1,inplace = True)

test.replace({',':'','\$':''},regex= True, inplace= True )
test.fillna(0, inplace=True)
test.index = range(len(test))
print(len(test))

2000

In [12]:
from sklearn import preprocessing

labels = preprocessing.LabelEncoder()

data.nppes_provider_gender = labels.fit_transform(data.nppes_provider_gender)
data.nppes_entity_code = labels.fit_transform(data.nppes_entity_code)
data.nppes_provider_city = labels.fit_transform(data.nppes_provider_city)
data.nppes_provider_zip5 = labels.fit_transform(data.nppes_provider_zip5)
data.nppes_provider_state = labels.fit_transform(data.nppes_provider_state)
data.specialty_description = labels.fit_transform(data.specialty_description)
data.medicare_prvdr_enroll_status = labels.fit_transform(data.medicare_prvdr_enroll_status)


test['nppes_provider_gender'] = test['nppes_provider_gender'].astype(str)
test['nppes_entity_code'] = test['nppes_entity_code'].astype(str)
test['nppes_provider_zip5'] = test['nppes_provider_zip5'].astype(str)
test['nppes_provider_state'] = test['nppes_provider_state'].astype(str)
test['specialty_description'] = test['specialty_description'].astype(str)


test.nppes_provider_gender = labels.fit_transform(test.nppes_provider_gender)
test.nppes_entity_code = labels.fit_transform(test.nppes_entity_code)
test.nppes_provider_city = labels.fit_transform(test.nppes_provider_city)
test.nppes_provider_zip5 = labels.fit_transform(test.nppes_provider_zip5)
test.nppes_provider_state = labels.fit_transform(test.nppes_provider_state)
test.specialty_description = labels.fit_transform(test.specialty_description)
test.medicare_prvdr_enroll_status = labels.fit_transform(test.medicare_prvdr_enroll_status)

In [13]:
Y = data.Preference
del data['Preference']
X = data

In [20]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import cross_val_score

clf_rf = RandomForestClassifier()
clf_rf.fit(X, Y)
print(clf_rf.feature_importances_)

print(X.columns)

accuracy = cross_val_score(clf_rf, X, Y, cv=5, scoring='accuracy')
print("Accuracy: {}".format(accuracy.mean()))
# precision = cross_val_score(clf_rf, X, Y, cv=5, scoring='precision')
# print("Precision: {}".format(precision.mean())) 
#recall = cross_val_score(clf_rf, X, Y, cv=5, scoring='recall')
#print("Recall: {} ".format(recall.mean()))
# f1 = cross_val_score(clf_rf, X, Y, cv=5, scoring='f1')
# print("F1: {} ".format(f1.mean()))
# auc = cross_val_score(clf_rf, X, Y, cv=5, scoring='roc_auc')
# print("AUC: {} ".format(auc.mean()))

[ 0.00239725  0.          0.01732894  0.01470753  0.01948065  0.0118735
  0.00387793  0.02811535  0.01458607  0.04972694  0.05616482  0.00061013
  0.03944973  0.46708461  0.00239725  0.          0.0188858   0.03844618
  0.01799321  0.02645845  0.00750721  0.00454605  0.0086336   0.01434569
  0.00352777  0.00284886  0.          0.00413603  0.00810812  0.00836532
  0.00195241  0.01357715  0.0063235   0.02319137  0.02071669  0.          0.
  0.          0.          0.0019397   0.01615913  0.0081698   0.01636729]
Index(['nppes_provider_gender', 'nppes_entity_code', 'nppes_provider_city',
       'nppes_provider_zip5', 'nppes_provider_state', 'specialty_description',
       'medicare_prvdr_enroll_status', 'total_claim_count',
       'total_30_day_fill_count', 'total_drug_cost', 'total_day_supply',
       'bene_count', 'brand_drug_cost', 'generic_drug_cost',
       'other_claim_count', 'other_drug_cost', 'mapd_claim_count',
       'mapd_drug_cost', 'pdp_claim_count', 'pdp_drug_cost', 'lis_claim_count',
       'lis_drug_cost', 'nonlis_claim_count', 'nonlis_drug_cost',
       'opioid_claim_count', 'opioid_drug_cost', 'opioid_day_supply',
       'opioid_bene_count', 'antibiotic_claim_count', 'antibiotic_drug_cost',
       'antibiotic_bene_count', 'average_age_of_beneficiaries',
       'beneficiary_female_count', 'beneficiary_male_count',
       'beneficiary_race_white_count', 'beneficiary_race_black_count',
       'beneficiary_race_asian_pi_count', 'beneficiary_race_hispanic_count',
       'beneficiary_race_nat_ind_count', 'beneficiary_race_other_count',
       'beneficiary_nondual_count', 'beneficiary_dual_count',
       'beneficiary_average_risk_score'],
      dtype='object')
Accuracy: 0.9965034965034965

In [15]:
ratio = pd.DataFrame(columns=['Preference'])
generic = test.generic_claim_count
brand = test.brand_claim_count

for row in range(len(brand)):
    generic[row] = str(generic[row]).replace(',','')
    brand[row] = str(brand[row]).replace(',','')
    
    if int(brand[row])!=0:
        ratio.loc[row] = float(generic[row])/float(brand[row])
    elif int(generic[row])!=0:
        ratio.loc[row] = generic[row]
    else:
        ratio.loc[row] = 0     

for index,row in enumerate(ratio.Preference):
    if(float(row)>=0):
        ratio.loc[index]='G'
    else:
        ratio.low[index]='B'
        
actual = ratio

C:\Users\sanke\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\sanke\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [16]:
del test['generic_claim_count']
del test['brand_claim_count']

In [17]:
from sklearn.metrics import accuracy_score

predictions = clf_rf.predict(test)
print(predictions)
print(actual)
accuracy_score(actual, predictions)

['G' 'G' 'G' ..., 'G' 'G' 'G']
     Preference
0             G
1             G
2             G
3             G
4             G
5             G
6             G
7             G
8             G
9             G
10            G
11            G
12            G
13            G
14            G
15            G
16            G
17            G
18            G
19            G
20            G
21            G
22            G
23            G
24            G
25            G
26            G
27            G
28            G
29            G
...         ...
1970          G
1971          G
1972          G
1973          G
1974          G
1975          G
1976          G
1977          G
1978          G
1979          G
1980          G
1981          G
1982          G
1983          G
1984          G
1985          G
1986          G
1987          G
1988          G
1989          G
1990          G
1991          G
1992          G
1993          G
1994          G
1995          G
1996          G
1997          G
1998          G
1999          G

[2000 rows x 1 columns]

0.77800000000000002